### ISSUE TITLE
体验

### ISSUE THREAD

**Issue by xu6148152** [chenupt/DragTopLayout#1]
还不错，但不够完善
外部的viewpager与内部的listview滑动无法连贯。相当于两个滚动是分开的
如果能做到将viewpager向上推，推到顶部后，不松手，能让内部内容滑动，这种效果是最好的。

**Comment by chenupt** [comment]
Fling 滑动效果是还有点小问题，但是基本上可以连贯滑动了。Thanks @sockeqwe.

**Comment by xu6148152** [comment]
基本上可以了，就差Fling的时候可能会导致滑动事件不连贯
