### ISSUE TITLE
is there a way to disable it

### ISSUE THREAD

**Issue by jjhesk** [chenupt/DragTopLayout#16]
I would like to ask if there is a method to disable the gesture method instead it will open only from the external call method.

**Comment by jjhesk** [comment]
it looks like on this method:

```java

  public DragTopLayout setTouchMode(boolean shouldIntercept) {
        this.shouldIntercept = shouldIntercept;
        return this;
    }

```

**Comment by chenupt** [comment]
Just setTouchMode(false)
