### ISSUE TITLE
[Request] Set collapse offset for TopView

### ISSUE THREAD

**Issue by kraizman** [chenupt/DragTopLayout#2]
Right now view collapsed completely. Is there way to set minimum offset so it will not collapse more then this minimum?

**Comment by yoavst** [comment]
+1

**Comment by vsahu1986** [comment]
+1

**Comment by chenupt** [comment]
It is coming soon.I have added a offset property in SetupWizard.It will be contained in 1.1.0 release.

**Comment by kraizman** [comment]
Thank you. Grate lib that come just in time.

**Comment by vsahu1986** [comment]
Thanks

**Comment by chenupt** [comment]
1.1.0 has released.
