### ISSUE TITLE
Trying to implement the ScrollView but I am not getting it to work.

### ISSUE THREAD

**Issue by eugeneisrambo** [chenupt/DragTopLayout#25]
I have a scroll view in the bottom content and no matter the position of the scrollvew, if you swipe up it pulls down the top view.  All in an activity, not a fragment,  I have implemented:

		public class MainActivity extends ActionBarActivity {
			private ScrollView scrollView;
			private DragTopLayout dragLayout;

			@Override
			protected void onCreate(Bundle savedInstanceState) {
				super.onCreate(savedInstanceState);
				setContentView(R.layout.activity_testing_diffent_views);
				scrollView = (ScrollView) findViewById(R.id.scroll_view);
				scrollView.setOnTouchListener(new View.OnTouchListener() {
					@Override
					public boolean onTouch(View v, MotionEvent event) {
						AttachUtil.isScrollViewAttach(scrollView);
						return false;
					}
				});
				dragLayout = (DragTopLayout) findViewById(R.id.drag_layout);
				dragLayout.toggleTopView();
				dragLayout.setOverDrag(false);

			}
		}

	<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
					xmlns:tools="http://schemas.android.com/tools"
					xmlns:app="http://schemas.android.com/apk/res-auto"
					android:layout_width="match_parent"
					android:layout_height="match_parent"
					tools:context=".MainActivity">

		<LinearLayout
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:background="@color/accent_material_dark"
			android:orientation="vertical">

			<android.support.v7.widget.Toolbar
				xmlns:app="http://schemas.android.com/apk/res-auto"
				android:id="@+id/tool_bar"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:background="?attr/colorPrimary"
				android:elevation="10dp"
				app:theme="@style/ThemeOverlay.AppCompat.Dark"
				app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
				android:minHeight="?attr/actionBarSize"/>

			<github.chenupt.dragtoplayout.DragTopLayout
				xmlns:app="http://schemas.android.com/apk/res-auto"
				android:background="@color/primary"
				android:id="@+id/drag_layout"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				>

				
				<LinearLayout
					android:id="@+id/top_view"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:animateLayoutChanges="true"
					android:gravity="center"
					android:orientation="vertical">

					<TextView
						android:id="@+id/text"
						android:text="Top View"
						android:textSize="18sp"
						android:textColor="@color/white"
						android:layout_gravity="center_horizontal"
						android:layout_margin="40dp"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"/>

					<ImageView
						android:id="@+id/image_view"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_gravity="center"
						android:layout_marginBottom="20dp"
						android:src="@drawable/ic_launcher"/>
				</LinearLayout>

				
				<LinearLayout
					android:orientation="vertical"
					android:id="@+id/drag_content_view"
					android:layout_width="match_parent"
					android:layout_height="match_parent">

					<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
								android:id="@+id/scroll_view"
								android:layout_width="match_parent"
								android:layout_height="match_parent">

						<LinearLayout
							android:layout_width="match_parent"
							android:layout_height="wrap_content"
							android:orientation="vertical">

							<ImageView
								android:src="@mipmap/water"
								android:adjustViewBounds="true"
								android:layout_width="match_parent"
								android:layout_height="wrap_content"/>

							<ImageView
								android:src="@mipmap/water"
								android:adjustViewBounds="true"
								android:layout_width="match_parent"
								android:layout_height="wrap_content"/>

							<ImageView
								android:src="@mipmap/water"
								android:adjustViewBounds="true"
								android:layout_width="match_parent"
								android:layout_height="wrap_content"/>

							<ImageView
								android:src="@mipmap/water"
								android:adjustViewBounds="true"
								android:layout_width="match_parent"
								android:layout_height="wrap_content"/>

							<ImageView
								android:src="@mipmap/water"
								android:adjustViewBounds="true"
								android:layout_width="match_parent"
								android:layout_height="wrap_content"/>
						</LinearLayout>
					</ScrollView>
				</LinearLayout>
			</github.chenupt.dragtoplayout.DragTopLayout>
		</LinearLayout>
	</RelativeLayout>
Any suggestion on getting this to work?

**Comment by chenupt** [comment]
Try:
```java
scrollView.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View v, MotionEvent event) {
                    dragLayout.setTouchMode(AttachUtil.isScrollViewAttach(scrollView));
                    return false;
                }
            });
```

Make sure dragLayout can intercept touch event at right time.

**Comment by eugeneisrambo** [comment]
@chenupt  Thanks for the working solution!  I can not believe it was that simple.
