### ISSUE TITLE
Better RecyclerView support

### ISSUE THREAD

**Issue by yoavst** [chenupt/DragTopLayout#3]
I can't scroll up on recyclerView like I can on ListView.

**Comment by vsahu1986** [comment]
+1

**Comment by chenupt** [comment]
It is the same way to set a Recyclerview.You should set your scroll listener to get the attach top time while you are scrolling just like ListView. I will add more samples to show how to use it in 1.1.0 release. 
A simple code:
```java
    @Override
    public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
        if (recyclerView.getChildCount() > 0) {
            if (recyclerView.getChildAt(0).getTop() >= 0) {
                setTouchMode(true);
            } else {
                setTouchMode(false);
            }
        }else{
            setTouchMode(true);
        }
    }

```

**Comment by chenupt** [comment]
1.1.0 has released.

**Comment by vsahu1986** [comment]
In AttachUtil for RecyclerView we are considering child zero top , what about the padding top , and the scroller speed . Like onScroll Listener we can find scolling speed and translate header accordingly
