### ISSUE TITLE
When setCollapseOffset is set RecyclerView is not scrolled until end

### ISSUE THREAD

**Issue by kraizman** [chenupt/DragTopLayout#5]
When i adding collapse offset my `RecyclerView` with `GridLayoutManager` not scrolled until end. Once i remove `collapseOffse`t all is good.

**Comment by chenupt** [comment]
You can use the snapshot with fixed bugs.
```java
maven {
    url "https://oss.sonatype.org/content/repositories/snapshots/"
}

compile 'com.github.chenupt.android:dragtoplayout:1.1.1-SNAPSHOT@aar'
```

**Comment by kraizman** [comment]
@chenupt Thank you. I will try it soon.

**Comment by kraizman** [comment]
@chenupt Looks like it not fix the issue. RecyclerView stile not scrolled until end. Reason can be that it populated later then wizard initiated. it probably should be some calculation that include offset as extension of max scrollY. In may case list is populated by loader

**Comment by chenupt** [comment]
Sorry I forgot to reset the content view height with the offset when the wizard initiated.In the least code I add a toggle to update content height when the offset is changed.Try it again:)

**Comment by kraizman** [comment]
Grate, looks like setting offset after population of RecyclerView do the job. One things that i notice:
I cannot use only *xml* attributes to setup *DragTopLayout* (like `dtlOpen="true"` and `dtlOverdrag="false"`). If i do not call `DragTopLayout.from(this).setup(dragLayout);` then views are not initialized correctly. It is not clear if i must call `.setup(dragTopView)` if I don't have any special setup calls on wizard. I would suggest to create wizard instance inside *DragTopLayout*. Put it as *public* getter in order to extend capabilities via code.

**Comment by chenupt** [comment]
You are right.It seems no need to call a setup for its init.I will try to make them as normal setters & getters for using.

**Comment by chenupt** [comment]
See #9
