### ISSUE TITLE
SetupWizard

### ISSUE THREAD

**Issue by sockeqwe** [chenupt/DragTopLayout#9]
I just wanted to ask, what is the idea behind having a `SetupWizard`? Probably I'm missing the point, but I can't see any reason why someone should use this wizard? The wizard only provides setter methods like  `setListener()`, `setCollapseOffset()` etc. right? So why not moving this methods directly to the `DragTopLayout` because the wizard is not creating a new instance of `DragTopLayout`, it only configures an existing one (which by the way can already be done with xml attributes).

I would expect that it should work like this in code (without `SetupWizard`):
```java
class MyActivity extends Activity {

    public void onCreate(Bundle saved) {
        super.onCreate(saved);
        setContentView(R.layout.my_layout);

         DragTopLayout dragTopLayout = (DragTopLayout) findViewById(R.id.dragTopLayout);
         dragTopLayout.setCollapseOffset(200)
                                  .setRefreshRatio(1.5)
                                  .setListener(new DragTopLayout.SimplePanelListener() {
                                       @Override
                                       public void onSliding(float ratio) {
                                            Log.d(TAG, "sliding: " + ratio);
                                        }
                                  });
         
    }

}
```

**Comment by chenupt** [comment]
It is true.The same issue from #5. All attributes work fine in the xml.I used setup just for setting its opening state and collapse offset before dragtopview being created so that view could to be corrected.But it seems to be more convenient if using setting & getting.I am trying to remove setupwizard in the next version.

**Comment by marcoRS** [comment]
:+1: Would be great to only have to configure from xml or with the proposed Api change. I find that I forget to use the setup wizard sometimes. 

Keep up the great work! Looking forward to the 1.1.1 release.

**Comment by chenupt** [comment]
I have removed the setupwizard and keep everything work fine.You can use it with the 1.2.0-SNAPSHOT. I will release it in this weekend.

**Comment by marcoRS** [comment]
Awesome! Keep up the great work!
